export const DEFAULT_STREAMING_SPEED_WPM = 200;
export const STREAMING_SPEED_MIN_WPM = 50;
export const STREAMING_SPEED_MAX_WPM = 500;

export const DEFAULT_ENABLE_POWER_POINTS = false;
export const DEFAULT_POWER_POINTS_VALUE = 15;
export const DEFAULT_TOSSUP_POINTS_VALUE = 10;
export const DEFAULT_TOSSUP_PENALTY_VALUE = 5;
export const DEFAULT_BONUS_PART_POINTS = 10;

export const DEFAULT_MULTIMODAL_REVEAL_LOCKOUT_SECONDS = 5;

export const DEFAULT_SUPPRESS_EARLY_AI_SECOND_BUZZES = true;
export const DEFAULT_TOSSUP_PENALTY_VALUE_SECOND_TEAM = 0;

